name: KiCad CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
            fetch-tags: 'true'
            fetch-depth: '0'

      - name: Set up KiCad
        uses: aseanwatson/setup-kicad@v1.1
        with:
          version: '9.0'

      - name: Run ERC
        run: |
          kicad-cli sch erc --output erc.txt KiCAD/DrumKitButtons.kicad_sch

      - name: Export BOM
        run: |
          kicad-cli sch export bom --output bom.csv KiCAD/DrumKitButtons.kicad_sch

      - name: Export Schematic PDF
        run: |
          kicad-cli sch export pdf --output schematic.pdf --define-var "REV=$(git describe --always)" KiCAD/DrumKitButtons.kicad_sch

      - name: Run DRC
        run: |
          kicad-cli pcb drc --output drc.txt KiCAD/DrumKitButtons.kicad_pcb

      - name: Export PCB PDF
        run: |
          kicad-cli pcb export pdf --output board-front.pdf --layers "User.Comments,Edge.Cuts,F.Silkscreen,F.Mask,F.Cu" --define-var "REV=$(git describe --always)" KiCAD/DrumKitButtons.kicad_pcb
          kicad-cli pcb export pdf --output board-back.pdf --layers "User.Comments,Edge.Cuts,B.Silkscreen,B.Mask,B.Cu" --mirror --define-var "REV=$(git describe --always)" KiCAD/DrumKitButtons.kicad_pcb

      - name: Export VRML 3D Board
        run: |
          kicad-cli pcb export vrml --output board.vrml --define-var "REV=$(git describe --always)" KiCAD/DrumKitButtons.kicad_pcb

      - name: Export STEP 3D Board
        run: |
          kicad-cli pcb export step --output board-full.step --include-tracks --include-zones --define-var "REV=$(git describe --always)" KiCAD/DrumKitButtons.kicad_pcb
          kicad-cli pcb export step --output board-only.step --board-only --include-tracks --include-zones --define-var "REV=$(git describe --always)" KiCAD/DrumKitButtons.kicad_pcb

      - name: Upload ERC
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ERC
          path: erc.txt
          retention-days: 15

      - name: Upload BOM
        uses: actions/upload-artifact@v4.4.3
        with:
          name: BOM
          path: bom.csv
          retention-days: 15

      - name: Upload Schematic PDF
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Schematic PDF
          path: schematic.pdf
          retention-days: 15

      - name: Upload DRC
        uses: actions/upload-artifact@v4.4.3
        with:
          name: DRC
          path: drc.txt
          retention-days: 15

      - name: Upload VRML 3D Model
        uses: actions/upload-artifact@v4.4.3
        with:
          name: VRML 3D Model
          path: board.vrml
          retention-days: 15

      - name: Upload STEP 3D Model
        uses: actions/upload-artifact@v4.4.3
        with:
          name: STEP 3D Model
          path: board-*.step
          retention-days: 15

      - name: Upload PCB PDF
        uses: actions/upload-artifact@v4.4.3
        with:
          name: PCB PDF
          path: board-*.pdf
          retention-days: 15
