name: KiCad CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'

      - name: Set up KiCad
        uses: actions-for-kicad/setup-kicad@v1.0
        with:
          version: '8.0'

      - name: Run ERC
        run: |
          kicad-cli sch erc -o erc.txt KiCAD/DrumKitButtons.kicad_sch

      - name: Export BOM
        run: |
          kicad-cli sch export -o bom.csv bom KiCAD/DrumKitButtons.kicad_sch

      - name: Export Schematic PDF
        run: |
          kicad-cli sch export pdf -o schematic.pdf -D "REV=$(git describe --dirty=-dirty)" KiCAD/DrumKitButtons.kicad_sch

      - name: Run DRC
        run: |
          kicad-cli pcb drc -o drc.txt KiCAD/DrumKitButtons.kicad_pcb

      - name: Export PCB PDF
        run: |
          kicad-cli pcb export pcb -o board.pdf -l "*" -D "REV=$(git describe --dirty=-dirty)" KiCAD/DrumKitButtons.kicad_sch

      - name: Export VRML 3D Board
        run: |
          kicad-cli pcb export vrml -o board.vrml -D "REV=$(git describe --dirty=-dirty)" KiCAD/DrumKitButtons.kicad_sch

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ERC
          path: erc.txt
          retention-days: 15

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BOM
          path: bom.csv
          retention-days: 15

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Schematic PDF
          path: schematic.pdf
          retention-days: 15

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DRC
          path: drc.txt
          retention-days: 15

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 3D Model
          path: board.vrml
          retention-days: 15

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PCB PDF
          path: board.pdf
          retention-days: 15

